services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_network

  python_app:
    build: .
    container_name: python_app_container
    depends_on:
      - redis
    networks:
      - redis_network

volumes:
  redis_data:

networks:
  redis_network:
    driver: bridge